spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgress
    password: password
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging level
logging:
  level:
    root: INFO
    com.github.pwnmn: DEBUG
